name: drag_container
description: 一个上拉抽屉效果
version: 0.0.1
homepage: https://github.com/zhaolongs/drag_container.git

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"



dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

